[project]
name = "mars-rover"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.13"
dependencies = [
  "aiohttp>=3.11.11",
  "asyncio>=3.4.3",
  "asyncpg>=0.30.0",
  "django~=5.0",
  "psycopg2>=2.9.10",
  "python-dotenv>=1.0.1",
]
