# Generated by Django 2.2.10 on 2020-02-08 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20200201_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol', models.IntegerField()),
                ('page', models.IntegerField()),
                ('rover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Rover')),
            ],
        ),
    ]
