# Generated by Django 3.0.2 on 2020-01-26 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rover',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('landing_date', models.DateField(default=None)),
                ('launch_date', models.DateField(default=None)),
                ('status', models.CharField(max_length=50)),
                ('max_sol', models.IntegerField()),
                ('max_date', models.DateField(default=None)),
                ('total_photos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sol', models.IntegerField()),
                ('img_src', models.CharField(max_length=200)),
                ('earth_date', models.DateField(default=None)),
                ('camera_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.Camera')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='rover_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.Rover'),
        ),
    ]
