# Generated by Django 5.1 on 2025-01-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rover',
            name='max_sol',
        ),
        migrations.AddField(
            model_name='job',
            name='max_sol',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
